title: Julian van den Berkmortel
url: https://serializator.github.io
author: Julian van den Berkmortel
email: julian.vandenberkmortel@privsecmail.com

description: >
  Cloud System Engineer with a security-first mindset; Inspired by Cloud & Open Source,
  contributing where and when I can.

remote_theme: https://github.com/mkchoi212/paper-jekyll-theme

footer_links:
  - url: https://github.com/Serializator
    text: GitHub

  - url: https://linkedin.com/in/jvandenberkmortel
    text: LinkedIn

plugins:
  - jekyll/tagging
